feat(icon): support for dynamic type
ionic-team/ionicons pull request #1246
Opened 2023-07-21 01:09 UTC by sean-perkins

Converts the usage of px units for fonts to rem.

2023-07-24 16:09 UTC, thetaPC commented
> Should this target a different branch instead of `main`?

Yes, it should target "FW-4146" branch instead of main.

2023-07-25 13:24 UTC, liamdebeasi requested changes
Can we add a screenshot test of icon being used with the text scaled up? Here's an example you can follow: https://github.com/ionic-team/ionic-framework/pull/27848/files#diff-2796ab1a929613b79f68ba352b11a68994e442070db3a7bbdbd7a1c0ded56c47R9-R26

(Note: previously the team discussed using a linter to ensure rem usage, but as I got more into development I realized some of these components are a bit more in-depth than I initially thought, so to be safe we're going to add a screenshot test)

2023-08-03 21:05 UTC, sean-perkins commented
@thetaPC it looks like the `FW-4146` branch is only on Ionic Framework's repository. Are you suggesting we create a similar branch here as well?

2023-08-03 21:15 UTC, thetaPC commented
> 

Oops, I misspoke. I though this was on the Framework repo. Disregard my comment.

2023-08-04 18:50 UTC, liamdebeasi commented on src/components/icon/test/icon.e2e.ts-snapshots/icon-diff-Mobile-Chrome-linux.png
Any idea why this screenshot changed?

2023-08-09 14:57 UTC, merged